### ISSUE TITLE
Unable to run on newer NPM versions;

### ISSUE THREAD

**Issue by Iratu** [funmaker/Hybooru#10]
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/www/hybooru/node_modules/chalk/source/index.js from /var/www/hybooru/server.js not supported.
Instead change the require of index.js in /var/www/hybooru/server.js to a dynamic import() which is available in all CommonJS modules.
    at Object.2242 (/var/www/hybooru/server.js:299:53971)
    at n (/var/www/hybooru/server.js:299:55518)
    at Object.8676 (/var/www/hybooru/server.js:1:62149)
    at n (/var/www/hybooru/server.js:299:55518)
    at /var/www/hybooru/server.js:299:55943
    at Object.<anonymous> (/var/www/hybooru/server.js:299:55952)
```

When using the latest version of NPM it will start with this error a quick google told me that they stopped supporting the require and now expect to be using the import() function.

**Comment by funmaker** [comment]
Hi, I've ran development and production builds using 8.1.4 npm and v17.2.0 node and couldn't replicate this issue.
What exact versions of npm and node are you using? Hydrus version? Have you tried to remove node_modules and reinstall all dependencies?
Also please include full output log, including command you were trying to run.

**Comment by Iratu** [comment]
Hiya,
I've tried the latest release v1.4.5, because it is a bit too much to paste here I've used a pastebin: https://pastebin.com/8TXwuh50 this is a fresh download and a new clean folder.

I'm also on NPM 8.1.4 and node 17.2.

**Comment by funmaker** [comment]
Alright, it seems I forgot to pin `chalk` version in package.json. The newest wersion is incompatible with my current webpack config.
Either way, I pinned the version to 4.x.x in the current release. Thanks for the issue, it should be fixed now.
