### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by Dividedby0KSJ** [funmaker/Hybooru#16]
I'm trying to build the program myself by following [Setup](https://github.com/funmaker/Hybooru#setup) & [Development](https://github.com/funmaker/Hybooru#development) but i keep getting errors when following the [Development](https://github.com/funmaker/Hybooru#development) steps.

with `npm run start` i get the error

```
PS Z:\Programs\Hybooru-master> npm run start

> hybooru@1.5.0-dev start
> rm -rf build && webpack --config webpack/server.dev.babel.js

'rm' is not recognized as an internal or external command,
operable program or batch file.

```

With `npm run build:prod` I get

```
PS Z:\Programs\Hybooru-master> npm run build:prod

> hybooru@1.5.0-dev build:prod
> mkdir -p dist && npm-run-all build:prod-*

'npm-run-all' is not recognized as an internal or external command,
operable program or batch file.
```
And the folder it makes is `-p` & `dist`

and with the last one `npm run start:prod`
```
PS Z:\Programs\Hybooru-master> npm run start:prod

> hybooru@1.5.0-dev start:prod
> cd dist && npm start

The system cannot find the path specified.
```

I'm trying to build it myself to use the new multiple tag repository.
I have been using the 1.4.8 release up till this point.

**Comment by funmaker** [comment]
Building on Windows is not supported. However, you can still look into `package.json` and change `scripts` to use Window's commands. Alternatively you can probably just use Docker or a virtual machine.

> I'm trying to build it myself to use the new multiple tag repository.
I will release that feature today.
