### ISSUE TITLE
 Hybooru halt at Resolving tag parents

### ISSUE THREAD

**Issue by beam7894123** [funmaker/Hybooru#17]
I using PowerShell to run all the command
```
npm start

> hybooru@1.5.0 start
> node server.js


HyBooru started on port 3939
Environment: production.
Press Ctrl-C to terminate.


Rebuilding Database!

Posts (11077/11077)             [####################] Done in 500ms
Urls (12716/12716)              [####################] Done in 611ms
Tags (8673/8673)                [####################] Done in 260ms
Mappings (84127/84127)          [####################] Done in 339ms
Mappings (50840/50840)          [####################] Done in 622ms
Tag parents (924/924)           [####################] Done in 58ms
Tag siblings (171/171)          [####################] Done in 9ms
Importing options...            [####################] Done in 24ms
Resolving file relations...     [####################] Done in 212ms
Normalizing tags (4/4)          [####################] Done in 192ms
Resolving tag parents...        [--------------------] 
```
After it halt, PostgreSQL staring to use more resource and my disk is gradually filling up until it full (my disk only have around 30GB of free space)
ever I `Terminate batch job`, it won't stop filling up the disk. I need to terminate PostgreSQL processor itseft to stop it 

I don't know this is a bug or not but i just want to let you know about this issue.

**Comment by beam7894123** [comment]
oh and btw i fix this issue by adding/changing this in `configs.json`
`"tags": { "resolveRelations": false },`

**Comment by funmaker** [comment]
Fixed in [v1.6.0](https://github.com/funmaker/Hybooru/releases/tag/v1.6.0). Reopen if the issue persists.

**Comment by NatureHog** [comment]
For some reason this issue still persists (at least for me...), even in 1.11.0?

I got the following error message:
`
Error: Connection terminated unexpectedly
at Connection.<anonymous> (/mnt/dietpi_userdata/Hybooru/node_modules/pg/lib/client.js:132:73)
at Object.onceWrapper (node:events:633:28)
at Connection.emit (node:events:519:28)
at Socket.<anonymous> (/mnt/dietpi_userdata/Hybooru/node_modules/pg/lib/connection.js:107:12)
at Socket.emit (node:events:531:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21)
`

Using [this](https://dietpi.com) Debian-based distro, everything still works, I just have to turn off tag relations for now...

**Comment by funmaker** [comment]
@NatureHog  This doesn't look like the same issue. You are losing the connection to the database.

Make a new issue, post full logs for what does work and what doesn't.

**Comment by NatureHog** [comment]
I'll look into it first myself, maybe I'm just doing something wrong, but I will open a separate issue when I've looked into it. Thanks!
