### ISSUE TITLE
[Feature Request] Use or specify which of multiple local file services

### ISSUE THREAD

**Issue by KentuckyFreudChicken** [funmaker/Hybooru#18]
The Hydrus dev seems to be all-in on this [multiple local file services](https://hydrusnetwork.github.io/hydrus/advanced_multiple_local_file_services.html) direction, and I've found it to be very helpful. I just set up Hybooru and saw that the configs.json at present doesn't allow us to specify which file service to use (or to use them all). Currently it pulls one of my local file services but not the other. Is this something you'd consider adding in the future? I know you did a lot of work to implement the multiple tag services feature, and I'm hoping there is a lot of crossover.

Thanks for all the great work making and maintaining Hybooru. It's a huge help and I appreciate it!

**Comment by funmaker** [comment]
Yeah, that's a feature I will probably utilize myself and integrate it into hydrus once I have some spare time.

**Comment by funmaker** [comment]
Implemented in [v1.6.0](https://github.com/funmaker/Hybooru/releases/tag/v1.6.0)
