### ISSUE TITLE
Support automated/scheduled database rebuilds

### ISSUE THREAD

**Issue by damianb** [funmaker/Hybooru#22]
Would like to perform regular rebuilds of the database, but unfortunately the endpoint to do so requires CSRF tokens which makes it rather annoying to automate.

If there could be a way implemented to trigger such via CLI or via REST interface with an API key or somesuch, it would be greatly appreciated.

**Comment by funmaker** [comment]
Will get rig of CSRF token in next version, since CSRF prevention is useless here as there is no session or cookies to hijack.

**Comment by funmaker** [comment]
Done in [v1.7.0](https://github.com/funmaker/Hybooru/releases/tag/v1.7.0)
