### ISSUE TITLE
[Feature Request] Hydrus Inbox filter/query support

### ISSUE THREAD

**Issue by LilianBoulard** [funmaker/Hybooru#25]
Hi, I'd like to disallow importing items from the Hydrus inbox (`system:inbox`), but blacklisting this tag in `configs.json` seems to have no effect.

**Comment by funmaker** [comment]
System tags are not real tags in hydrus but a special commands that allow for querying various file metadata. They are hardcoded inside hydurs and hybooru would have to reimplement them to add support. Right now hybooru supports its own system tags such as `rating`, `sort` and `order` and I do not plan to add more for time being.

However PRs are welcomed. If you'd like to give it a go yourself, you probably will be interested in `/server/helpers/dbImport/posts.ts` to extend file metadata that is being imported and then functions `applyBlacklist`/`applyWhitelist` in `/server/helpers/dbImport/index.ts` for blacklist/whitelist during import and `/server/controllers/posts.ts` for actual searching

**Comment by funmaker** [comment]
Added in 1.10.0
