### ISSUE TITLE
MOTD multiple tag support

### ISSUE THREAD

**Issue by Wyrrrd** [funmaker/Hybooru#3]
I want to filter out full comic pages from motd, but the `tags.motd` setting seems to support only one positive tag. When I add a whitespace or dash to that string, the motd disappears after reload.

`"tags.motd": "one"` - works
`"tags.motd": "one two"` - does not work
`"tags.motd": "-one"` - does not work
`"tags.motd": "one -two"` - does not work

Unsure if this works as intended... If yes, you could add a short info to config docs.

**Comment by funmaker** [comment]
Yes, this is intended behavior. motd support only a single tag pattern, not a full query. I'll make it more explicit in README.md.
