### ISSUE TITLE
Getting an error, so close to getting this done, no clue where to start

### ISSUE THREAD

**Issue by FurretGod** [funmaker/Hybooru#30]
hi, i'm furret, i know little to nothing about coding and i want to make a booru for my friends to host old images, memes. etc. i figured out all of the config stuff after hours, and now i'm stumped, as whenever i run "npm start", i simply get this error

> hybooru@1.7.1 start
> node server.js

```
HyBooru started on port 3939
Environment: production.
Press Ctrl-C to terminate.

Database update detected, rebuilding...

Rebuilding Database!

Unable to initialize DB!
TypeError: Cannot open database because the directory does not exist
    at new Database (C:\Users\Furret\Desktop\furretbooru\node_modules\better-sqlite3\lib\database.js:59:9)
    at Object.<anonymous> (C:\home\runner\work\Hybooru\Hybooru\server\helpers\dbImport\index.ts:53:20)
    at Generator.next (<anonymous>)
    at o (C:\Users\Furret\Desktop\furretbooru\server.js:178:4048)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

i figured out what "`at new Database (C:\Users\Furret\Desktop\furretbooru\node_modules\better-sqlite3\lib\database.js:59:9)`" was referring to, as going to that location shows up the error code it sent, but for the next line, the path "`C:\home\runner\work\Hybooru\Hybooru\server\helpers\dbImport\index.ts:53:20`" doesn't even exist, much less `C:\home`. i'm really struggling here and i hope someone is able to help me, thank you in advance

**Comment by funmaker** [comment]
Do you have hydrus installed? If so, is it in default location?
Also post your configs.json from hybooru. Redact `adminPassword` if you set any.

**Comment by funmaker** [comment]
I assume you've either figured it out or given up. Closing for now.
If anyone else faces this problem make sure you have Hydrus installed and Hybooru properly configured to point it to Hydru's database location.
