### ISSUE TITLE
Don't force port 80 when DOCKERIZED

### ISSUE THREAD

**Issue by alnmy** [funmaker/Hybooru#36]
Currently, the Dockerfile sets an environment variable, "DOCKERIZED", to 1 and this forces Hybooru to run on port 80.
I am using rootless Podman on my server which means that containers cannot use port 80. I would propose that the "DOCKERIZED" environment variable is kept however that the port can be changed if an environment variable such as "PORT" is used.

**Comment by funmaker** [comment]
As of 1.10.0 you can use PORT envvar. DOCKERIZED is no longer used.
