### ISSUE TITLE
[Feature Request] Allow configuring host from `configs.json`

### ISSUE THREAD

**Issue by Xunnamius** [funmaker/Hybooru#38]
Hi there, thanks for this neat project.

It'd be nice if we could configure the host used by `http.CreateServer`. To this end [I've added `server.listen(port, 'localhost');` in my fork](https://github.com/Xunnamius/hydribooru/commit/e6b0d64745a5780b1779f451f63056308d1ca37d), but that's hackier than official config-based support.

**Comment by funmaker** [comment]
Added in v1.10.0
