### ISSUE TITLE
Rework the Database

### ISSUE THREAD

**Issue by ReconVirus** [funmaker/Hybooru#41]
In part of the ongoing development process, I propose reworking the database import process to improve efficiency and maintain data integrity. Currently, users are required to delete the entire dataset before sending a rebuilding, request which can be time-consuming. Instead, Im sure alot of end users would  recommend implementing an incremental update approach:

1. **Incremental Updates**: Modify the import process to identify changes since the last import. Only new or updated data should be processed, minimizing the need for a full reimport.

2. **Selective Deletion**: When necessary, selectively delete outdated records based on the changes detected during the import. This approach ensures that existing data remains intact while accommodating necessary updates.

Im sure this request has been brought to your attention , so i figure i would post this as a issue(request).

**Comment by funmaker** [comment]
Incremental database updates are not in the scope for me. It would greatly increase complexity of the import process.
I know that it might be inconvenient for people with larger databases that get updated frequently, however for my own personal usecases this is not an issue.

However since many people asked for it, I will leave this issue open in case someone wants to try implementing it and/or discuss possible solutions.

**Comment by ReconVirus** [comment]
> ...discuss possible solutions.

My best guess would be to add something like 
```typescript
    // Incremental Updates
    const lastImportTime = await this.getLastImportTime(); // Retrieve the last import time from the database
    await this.updateLastImportTime(Date.now()); // Update the last import time after a successful import
    
    // Selective Deletion
    const outdatedRecords = await this.getOutdatedRecords(lastImportTime); // Retrieve outdated records based on the last import time
    await this.deleteOutdatedRecords(outdatedRecords); // Delete outdated records
```
    
which can be stored in the postgress datebase for future reference
```Sql
CREATE TABLE import_status (
  id SERIAL PRIMARY KEY,
  last_import_time TIMESTAMP DEFAULT NOW()
);
```
an alternative to this might just be using hydrus version number seeing how you're already using that in your index.ts
```typescript
const { version } = hydrus.prepare('SELECT version FROM version;').get();
    if(version < MIN_HYDRUS_VER) throw new Error(`Unsupported Hydrus version(min: v${MIN_HYDRUS_VER}, current: v${version}), Update Hydrus to the newest version.`);
```
which could be a safe approach to allowing the user to import changes between versions without the need of a full on rebuild.

As far as me actually implementing this... I honestly wouldnt know where to start .

**Comment by ReconVirus** [comment]
> Incremental database updates are not in the scope for me. It would greatly increase complexity of the import process.
> I know that it might be inconvenient for people with larger databases that get updated frequently, however for my own personal usecases this is not an issue.

ill just close this out as not planned , took me almost 2 weeks to get what you were saying 😂
