### ISSUE TITLE
`Connection terminated unexpectedly` while resolving tags relations

### ISSUE THREAD

**Issue by NatureHog** [funmaker/Hybooru#42]
Using v1.11.0 with latest npm deps, on a Raspberry Pi 3 running [this](https://dietpi.com) Debian (bookworm)-based distro.

Everytime I set the configs.json value of "resolveRelations" to "true", and rebuild the db afterwards, the program(?) always loses connection to the db, restarting the server with a somewhat broken db, i.e. pictures not being loaded, thumbnails missing.

The related error is as follows:
```
/mnt/dietpi_userdata/Hybooru/node_modules/pg/lib/client.js:132
      const error = this._ending ? new Error('Connection terminated') : new Error('Connection terminated unexpectedly')
                                                                        ^
Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/mnt/dietpi_userdata/Hybooru/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:633:28)
    at Connection.emit (node:events:519:28)
    at Socket.<anonymous> (/mnt/dietpi_userdata/Hybooru/node_modules/pg/lib/connection.js:107:12)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
(node:232401) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

The database config has been left at default, both in configs.json and the PostgreSQL install.

**Comment by funmaker** [comment]
Post entire hybooru log. Also check database and system logs, maybe you are running out of ram or other resource and your database server is restarting.

**Comment by NatureHog** [comment]
I'm using the standard `npm start` command inside the install directory and the complete log can be found in a Gist [here](https://gist.github.com/NatureHog/d4d6fa021b81d33e58e3868fc7d4893a).

**Comment by funmaker** [comment]
Well, that's clearly just PostgreSQL crashing. Which version of PostgreSQL are you using? Are you using any non trusted extensions or some C-language psql functions?
Try to update PostgreSQL to the newest version.

If that doesn't help then there is only the hard way left. You will have to get a readable stacktrace using this guide: https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Linux/BSD
After that we might get some idea, but it is also possible it's just some postgresql bug that will have to be reported to them.

**Comment by NatureHog** [comment]
I'm running PostgreSQL version 15, using a fresh install, and only "creating" the extensions listed in the instructions.

The only modification made by the install script I used is explained [here](https://dietpi.com/docs/software/databases/#__tabbed_6_1). As such the instructions from those docs have been followed.

The only thing I've noticed is that Hybooru doesn't _seem_ to work with UNIX sockets, but maybe that's my personal inexperience with Unix talking...

**Comment by funmaker** [comment]
> The only thing I've noticed is that Hybooru doesn't seem to work with UNIX sockets, but maybe that's my personal inexperience with Unix talking...

Works on my machine

```
...
    "db": {
        "user": "hybooru",
        "host": "/var/run/postgresql",
        "database": "hybooru",
        "password": "...",
        "port": 5432
    },
...
```
```
$ npm start        

> hybooru@1.11.0 start
> node server.js


HyBooru started on port 3940
Environment: production.
Press Ctrl-C to terminate.

Fetching resources
```

**Comment by NatureHog** [comment]
Ok, like I said, I'm not very experienced with Unix, but I will try it when I get to it, similar to a useful stacktrace.

**Comment by NatureHog** [comment]
Since my previous comment, I have fixed my issue, by simply using a different OS entirely.

I had several issues with the previous OS mentioned above regardless, but since it's now working for me, I'm going to close this.
