### ISSUE TITLE
Switching between alternate videos does not update the video player

### ISSUE THREAD

**Issue by gfieldGG** [funmaker/Hybooru#46]
When switching between (autoplaying) alternate video files via the right sidebar the page content updates but the video player keeps playing the old file.

The <source> element gets the new url but the player itself doesn't notice/update.
Sometimes the player slighty resizes towards the alternate files' aspect ratio.
Switching back and forth updates the url and other page content but never the video player.
Images work fine.

Tested on Chrome and Firefox using Hybooru v1.12.1 Docker image.

**Comment by funmaker** [comment]
Fixed as of v1.12.2
